### ISSUE TITLE
NotUniqueError

### ISSUE THREAD

**Issue by jhill1** [supertree-toolkit/stk#4]
kd528@kd528-mac ~/Documents/Temp120218/6.DataIndependence $ stk data_ind -o dataInd.txt -n 6.CicadaDataInd.phyml 5.CicadaFinalSubbed.phyml 
Traceback (most recent call last):
  File "/usr/local/bin/stk", line 2399, in <module>
    main()
  File "/usr/local/bin/stk", line 594, in main
    args.func(args)
  File "/usr/local/bin/stk", line 710, in data_ind
    except supertree_toolkit.NotUniqueError as detail:
AttributeError: 'module' object has no attribute 'NotUniqueError'

Easy fix. Check for other instances.

**Comment by jhill1** [comment]
May be fixed in autotree branch, so may be a matter of a new release to fix this issue.
