### ISSUE TITLE
Error in carrying out autosubs

### ISSUE THREAD

**Issue by cjnaylor** [supertree-toolkit/stk#6]
***Error: failed to carry out auto subs due to unknown error. File a bug report, please!
https://github.com/supertree-toolkit/stk/issues
Traceback (most recent call last):
  File "/home/stk/supertree_toolkit.py", line 1648, in autoprocess
    phyml = generate_species_level_data(phyml,taxonomy,verbose=verbose)
  File "/home/stk/supertree_toolkit.py", line 770, in generate_species_level_data
    if ('species' in taxonomy[taxon]):
KeyError: 'Acangaobitermes krishnai'

**Comment by jhill1** [comment]
Looks like the key "Acangaobitermes krishnai" is missing the _ (i.e. should be a "_" not a space). 
Have a look at the taonxomy file generated in the previous step (in Excel or similar) and check the OTU column has _ not spaces.
Then look around line 770 in supertree_toolkit.py and check where the taxa list comes from, i.e. there'll be a line that is:
`taxa = stk.get...blah`
There might need to be a line in the loop that goes over taxa to do a replace:
`taxon = taxon.replace(" ","_")`
at the start of that loop.
